// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: bank_account.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (
  user_id,
  bank_name,
  bank_account_name,
  bank_account_number
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id, bank_name, bank_account_name, bank_account_number, created_at
`

type CreateBankAccountParams struct {
	UserID            uuid.UUID `json:"user_id"`
	BankName          string    `json:"bank_name"`
	BankAccountName   string    `json:"bank_account_name"`
	BankAccountNumber string    `json:"bank_account_number"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, createBankAccount,
		arg.UserID,
		arg.BankName,
		arg.BankAccountName,
		arg.BankAccountNumber,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankName,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getBankAccountsByUserId = `-- name: GetBankAccountsByUserId :many
SELECT id, bank_name, bank_account_name, bank_account_number FROM bank_accounts
WHERE user_id = $1
`

type GetBankAccountsByUserIdRow struct {
	ID                uuid.UUID `json:"id"`
	BankName          string    `json:"bank_name"`
	BankAccountName   string    `json:"bank_account_name"`
	BankAccountNumber string    `json:"bank_account_number"`
}

func (q *Queries) GetBankAccountsByUserId(ctx context.Context, userID uuid.UUID) ([]GetBankAccountsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getBankAccountsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBankAccountsByUserIdRow{}
	for rows.Next() {
		var i GetBankAccountsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.BankName,
			&i.BankAccountName,
			&i.BankAccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
